# Copyright 2026 SimmerChan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Framework Adapters - PyTorch/TensorFlow适配器生成

支持:
- PyTorch CustomOpInterface 适配
- TensorFlow Custom Crowd Operator 适配
"""

import logging
from dataclasses import dataclass, field
from typing import Optional

from ascend_op_agent.workflow.models import (
    CodeGenResult,
    DesignDoc,
    FileChange,
    OpInfo,
)

logger = logging.getLogger(__name__)


def _to_pascal_case(name: str) -> str:
    """将snake_case转换为PascalCase"""
    return "".join(word.capitalize() for word in name.split("_"))


@dataclass
class AdapterResult:
    """适配器生成结果"""
    success: bool
    files: list[FileChange] = field(default_factory=list)
    generated_files: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    framework: str = ""


class FrameworkAdapter:
    """框架适配器基类"""

    def __init__(self, op_info: OpInfo, design_doc: DesignDoc):
        self.op_info = op_info
        self.design_doc = design_doc

    def generate(self) -> AdapterResult:
        """生成适配代码"""
        raise NotImplementedError


class PyTorchAdapter(FrameworkAdapter):
    """PyTorch适配器

    生成PyTorch CustomOpInterface格式的适配代码。
    支持:
    - torch.library.custom_op
    - torch.autograd.Function
    - torch.nn.Module封装
    """

    def __init__(self, op_info: OpInfo, design_doc: DesignDoc):
        super().__init__(op_info, design_doc)

    def generate(self) -> AdapterResult:
        """生成PyTorch适配代码"""
        files = []
        generated_files = []

        try:
            # 生成CustomOp实现
            custom_op_code = self._generate_custom_op()
            custom_op_file = f"torch_{self.op_info.name}_op.cpp"
            files.append(FileChange(
                path=custom_op_file,
                action="create",
                content=custom_op_code,
            ))
            generated_files.append(custom_op_file)

            # 生成Python封装
            py_wrapper_code = self._generate_python_wrapper()
            py_wrapper_file = f"torch_{self.op_info.name}_wrapper.py"
            files.append(FileChange(
                path=py_wrapper_file,
                action="create",
                content=py_wrapper_code,
            ))
            generated_files.append(py_wrapper_file)

            # 生成测试代码
            test_code = self._generate_pytorch_test()
            test_file = f"test_torch_{self.op_info.name}.py"
            files.append(FileChange(
                path=test_file,
                action="create",
                content=test_code,
            ))
            generated_files.append(test_file)

            return AdapterResult(
                success=True,
                files=files,
                generated_files=generated_files,
                framework="pytorch",
            )

        except Exception as e:
            logger.error(f"PyTorch adapter generation failed: {e}")
            return AdapterResult(
                success=False,
                errors=[str(e)],
                framework="pytorch",
            )

    def _generate_custom_op(self) -> str:
        """生成CustomOp C++实现"""
        input_types = ", ".join(self._map_dtype_to_torch(self.op_info.input_dtypes))
        output_types = ", ".join(self._map_dtype_to_torch(self.op_info.output_dtypes))

        return f'''// PyTorch CustomOp for {self.op_info.name}
// Generated by Ascend Op Agent

#include <torch/extension.h>
#include "kernel_{self.op_info.name}.h"

// 向前传播
at::Tensor {self.op_info.name}_forward(
    at::Tensor input
) {{
    // 调用AscendC算子
    // TODO: 实现实际的算子调用
    return input;
}}

// 向后传播
std::vector<at::Tensor> {self.op_info.name}_backward(
    at::Tensor grad_output
) {{
    // 梯度计算
    return {{grad_output}};
}}

// 注册CustomOp
TORCH_LIBRARY(ascend, m) {{
    m.def("{self.op_info.name}_forward");
    m.def("{self.op_info.name}_backward");
}}

TORCH_LIBRARY_IMPL(ascend, CompositeExplicitAutograd, m) {{
    m.impl("{self.op_info.name}_forward", &{self.op_info.name}_forward);
    m.impl("{self.op_info.name}_backward", &{self.op_info.name}_backward);
}};
'''

    def _generate_python_wrapper(self) -> str:
        """生成Python封装"""
        input_shapes_str = str(self.op_info.input_shapes[0]) if self.op_info.input_shapes else "[1]"
        output_shape_str = str(self.op_info.output_shapes[0]) if self.op_info.output_shapes else "[1]"

        return f'''# PyTorch Wrapper for {self.op_info.name}
# Generated by Ascend Op Agent

import torch
from typing import List, Optional

class {_to_pascal_case(self.op_info.name)}Op(torch.autograd.Function):
    """自定义算子封装"""

    @staticmethod
    def forward(ctx, input: torch.Tensor) -> torch.Tensor:
        # 保存用于反向传播的tensor
        ctx.save_for_backward(input)
        # 调用自定义算子
        output = torch.ops.ascend.{self.op_info.name}_forward(input)
        return output

    @staticmethod
    def backward(ctx, grad_output: torch.Tensor) -> tuple:
        input, = ctx.saved_tensors
        # 调用反向算子
        grad_input = torch.ops.ascend.{self.op_info.name}_backward(grad_output)
        return grad_input


class {_to_pascal_case(self.op_info.name)}Module(torch.nn.Module):
    """{self.op_info.description}算子模块"""

    def __init__(self):
        super().__init__()

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return {_to_pascal_case(self.op_info.name)}Op.apply(input)


def {self.op_info.name}(
    input: torch.Tensor,
    *,
    out: Optional[torch.Tensor] = None
) -> torch.Tensor:
    """
    {self.op_info.description}

    Args:
        input: 输入tensor, shape: {input_shapes_str}

    Returns:
        输出tensor, shape: {output_shape_str}
    """
    return torch.ops.ascend.{self.op_info.name}_forward(input)
'''

    def _generate_pytorch_test(self) -> str:
        """生成PyTorch测试代码"""
        return f'''# PyTorch Test for {self.op_info.name}
# Generated by Ascend Op Agent

import torch
import pytest
from torch_{self.op_info.name}_wrapper import {_to_pascal_case(self.op_info.name)}Module


class Test{_to_pascal_case(self.op_info.name)}Op:
    """测试{self.op_info.name}算子"""

    def test_basic_forward(self):
        """测试基本前向传播"""
        module = {_to_pascal_case(self.op_info.name)}Module()
        x = torch.randn(32, 32, dtype=torch.float32)
        y = module(x)
        assert y.shape == x.shape

    def test_dtype_float32(self):
        """测试float32类型"""
        module = {_to_pascal_case(self.op_info.name)}Module()
        x = torch.randn(16, 16, dtype=torch.float32)
        y = module(x)
        assert y.dtype == torch.float32

    def test_dtype_float16(self):
        """测试float16类型"""
        module = {_to_pascal_case(self.op_info.name)}Module()
        x = torch.randn(16, 16, dtype=torch.float16)
        y = module(x)
        assert y.dtype == torch.float16

    def test_gradient(self):
        """测试梯度计算"""
        module = {_to_pascal_case(self.op_info.name)}Module()
        x = torch.randn(8, 8, dtype=torch.float32, requires_grad=True)
        y = module(x)
        loss = y.sum()
        loss.backward()
        assert x.grad is not None


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''

    def _map_dtype_to_torch(self, dtypes: list[str]) -> list[str]:
        """将dtype映射为PyTorch类型"""
        dtype_map = {
            "float32": "torch.float32",
            "float16": "torch.float16",
            "int8": "torch.int8",
            "int32": "torch.int32",
            "int64": "torch.int64",
            "bool": "torch.bool",
        }
        return [dtype_map.get(dt, "torch.float32") for dt in dtypes]


class TensorFlowAdapter(FrameworkAdapter):
    """TensorFlow适配器

    生成TensorFlow Custom Crowd Operator格式的适配代码。
    支持:
    - tf.raw_ops py binding
    - tf.function
    """

    def __init__(self, op_info: OpInfo, design_doc: DesignDoc):
        super().__init__(op_info, design_doc)

    def generate(self) -> AdapterResult:
        """生成TensorFlow适配代码"""
        files = []
        generated_files = []

        try:
            # 生成Custom Op实现
            op_code = self._generate_custom_op()
            op_file = f"tf_{self.op_info.name}_op.cc"
            files.append(FileChange(
                path=op_file,
                action="create",
                content=op_code,
            ))
            generated_files.append(op_file)

            # 生成Python封装
            py_wrapper_code = self._generate_python_wrapper()
            py_wrapper_file = f"tf_{self.op_info.name}_wrapper.py"
            files.append(FileChange(
                path=py_wrapper_file,
                action="create",
                content=py_wrapper_code,
            ))
            generated_files.append(py_wrapper_file)

            # 生成测试代码
            test_code = self._generate_tf_test()
            test_file = f"test_tf_{self.op_info.name}.py"
            files.append(FileChange(
                path=test_file,
                action="create",
                content=test_code,
            ))
            generated_files.append(test_file)

            return AdapterResult(
                success=True,
                files=files,
                generated_files=generated_files,
                framework="tensorflow",
            )

        except Exception as e:
            logger.error(f"TensorFlow adapter generation failed: {e}")
            return AdapterResult(
                success=False,
                errors=[str(e)],
                framework="tensorflow",
            )

    def _generate_custom_op(self) -> str:
        """生成Custom Op C++实现"""
        return f'''// TensorFlow CustomOp for {self.op_info.name}
// Generated by Ascend Op Agent

#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"

namespace tensorflow {{

class {_to_pascal_case(self.op_info.name)}Op : public OpKernel {{
public:
    explicit {_to_pascal_case(self.op_info.name)}Op(OpKernelConstruction* context)
        : OpKernel(context) {{}}

    void Compute(OpKernelContext* context) override {{
        // 获取输入tensor
        const Tensor& input = context->input(0);

        // 创建输出tensor
        Tensor* output = nullptr;
        OP_REQUIRES_OK(context,
            context->allocate_output(0, input.shape(), &output));

        // 调用AscendC算子
        // TODO: 实现实际的算子调用

        // 复制输入到输出（示例）
        output->flat<float>().device(context->eigen_cpu_device()) =
            input.flat<float>();
    }}
}};

REGISTER_KERNEL_BUILDER(
    Name("{self.op_info.name}").Device(DEVICE_CPU),
    {_to_pascal_case(self.op_info.name)}Op);

}}  // namespace tensorflow
'''

    def _generate_python_wrapper(self) -> str:
        """生成Python封装"""
        input_shapes_str = str(self.op_info.input_shapes[0]) if self.op_info.input_shapes else "[1]"
        output_shape_str = str(self.op_info.output_shapes[0]) if self.op_info.output_shapes else "[1]"

        return f'''# TensorFlow Wrapper for {self.op_info.name}
# Generated by Ascend Op Agent

import tensorflow as tf
from typing import Optional

# 加载自定义算子
try:
    _op = tf.load_op_library('./libtf_{self.op_info.name}.so')
    {self.op_info.name}_op = _op.{self.op_info.name}
except Exception:
    tf.logging.warning("Failed to load custom op library")


class {_to_pascal_case(self.op_info.name)}Layer(tf.keras.layers.Layer):
    """{self.op_info.description}算子层"""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, inputs):
        if '{self.op_info.name}_op' in dir():
            return {self.op_info.name}_op(inputs)
        else:
            # Fallback to numpy implementation for testing
            import numpy as np
            return tf.constant_numpy = lambda x: tf.constant(x.numpy())
            return inputs

    def get_config(self):
        return super().get_config()


@tf.function
def {self.op_info.name}(
    input_tensor: tf.Tensor,
    name: Optional[str] = None
) -> tf.Tensor:
    """
    {self.op_info.description}

    Args:
        input_tensor: 输入tensor, shape: {input_shapes_str}
        name: 操作名称

    Returns:
        输出tensor, shape: {output_shape_str}
    """
    return {self.op_info.name}_op(input_tensor, name=name)
'''

    def _generate_tf_test(self) -> str:
        """生成TensorFlow测试代码"""
        return f'''# TensorFlow Test for {self.op_info.name}
# Generated by Ascend Op Agent

import tensorflow as tf
import numpy as np
import pytest


class Test{_to_pascal_case(self.op_info.name)}Op:
    """测试{self.op_info.name}算子"""

    def test_basic_forward(self):
        """测试基本前向传播"""
        x = tf.random.normal([32, 32], dtype=tf.float32)
        try:
            y = {self.op_info.name}(x)
            assert y.shape == x.shape
        except Exception as e:
            pytest.skip(f"Custom op not available: {{e}}")

    def test_dtype_float32(self):
        """测试float32类型"""
        x = tf.random.normal([16, 16], dtype=tf.float32)
        try:
            y = {self.op_info.name}(x)
            assert y.dtype == tf.float32
        except Exception:
            pass

    def test_dtype_float16(self):
        """测试float16类型"""
        x = tf.random.normal([16, 16], dtype=tf.float16)
        try:
            y = {self.op_info.name}(x)
            assert y.dtype == tf.float16
        except Exception:
            pass

    def test_gradient(self):
        """测试梯度计算"""
        x = tf.Variable(tf.random.normal([8, 8], dtype=tf.float32))
        try:
            with tf.GradientTape() as tape:
                y = {self.op_info.name}(x)
            grad = tape.gradient(y, x)
            assert grad is not None
        except Exception:
            pass


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''


def generate_framework_adapter(
    op_info: OpInfo,
    design_doc: DesignDoc,
    framework: str,
) -> AdapterResult:
    """生成框架适配器的工厂函数

    Args:
        op_info: 算子信息
        design_doc: 设计文档
        framework: 框架类型 ("pytorch" 或 "tensorflow")

    Returns:
        AdapterResult: 适配器生成结果
    """
    if framework.lower() == "pytorch":
        adapter = PyTorchAdapter(op_info, design_doc)
    elif framework.lower() == "tensorflow":
        adapter = TensorFlowAdapter(op_info, design_doc)
    else:
        return AdapterResult(
            success=False,
            errors=[f"Unsupported framework: {framework}"],
        )

    return adapter.generate()
