# Copyright 2026 SimmerChan
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

"""Tests for U2 Layer 6 rewrite (A1 token-budget fix + F-4 degradation)."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import pytest


VALID_BODY = "## Project Scope\n\nApplies to 910B3.\n"


def _use_tmp_storage(tmp_path, monkeypatch):
    """Route every ``SkillStorage()`` call inside the tool/Layer 6 to ``tmp_path``."""
    from ascend_op_agent.skills import storage as storage_mod
    _orig_init = storage_mod.SkillStorage.__init__

    def _init(self, skills_dir=None):
        _orig_init(self, skills_dir=str(tmp_path))

    monkeypatch.setattr(storage_mod.SkillStorage, "__init__", _init)


def _create_skill(storage, name: str, task_type: str = "develop", topic: str = "tiling"):
    """Write a self-built SKILL.md directly via storage."""
    from ascend_op_agent.skills.models import Skill
    skill = Skill(
        name=name,
        description="autogenerated for U2 test",
        content=VALID_BODY,
        metadata={
            "write_origin": "test",
            "write_origin": "manual",  # last wins
            "task_type": task_type,
            "topic": topic,
        },
    )
    storage.save_skill(skill, dimension="self_built")


def test_default_path_emits_only_self_built_no_cannbot(tmp_path, monkeypatch):
    """A1 fix: default path must NOT render cannbot. /learn chat doesn't
    need cannbot phase knowledge; rendering all 16 cannbot SKILLs blows the
    800-tok budget (894 tok measured)."""
    _use_tmp_storage(tmp_path, monkeypatch)
    from ascend_op_agent.agent.prompt_builder import PromptBuilder
    from ascend_op_agent.skills.storage import SkillStorage

    pb = PromptBuilder()
    storage = SkillStorage()
    _create_skill(storage, "tiling-pitfalls", task_type="develop")

    out = pb._build_skills_layer(override=None, task_type=None)
    assert "## Available Skills" in out
    assert "tiling-pitfalls" in out
    # No cannbot names should leak (cannbot names like cuda2ascend-simt absent)
    assert "cuda2ascend-simt" not in out


def test_production_path_merges_override_with_self_built(tmp_path, monkeypatch):
    """Production path (override non-None, PhaseRunner node): override precedes
    self-built section, both visible."""
    _use_tmp_storage(tmp_path, monkeypatch)
    from ascend_op_agent.agent.prompt_builder import PromptBuilder
    from ascend_op_agent.skills.storage import SkillStorage

    pb = PromptBuilder()
    storage = SkillStorage()
    _create_skill(storage, "tiling-pitfalls", task_type="develop")
    _create_skill(storage, "cann-runtime-debug", task_type="migrate")

    override = "## Skills (phase=design)\n- cuda2ascend-simt: desc"
    out = pb._build_skills_layer(override=override, task_type="design")

    assert "cuda2ascend-simt" in out  # cannbot (override) appears
    assert "tiling-pitfalls" in out   # self-built appears


def test_production_path_with_no_self_built_keeps_override_only(tmp_path):
    """If override is non-None but no self-built skills exist, return override intact."""
    from ascend_op_agent.agent.prompt_builder import PromptBuilder

    pb = PromptBuilder()
    override = "## Skills (phase=design)\n- cuda2ascend-simt: desc"
    out = pb._build_skills_layer(override=override, task_type="design")
    assert out == override


def test_default_path_with_no_self_built_emits_prompt_to_use_learn(tmp_path, monkeypatch):
    """Default path with empty self-built/ shows hint about /learn CLI."""
    _use_tmp_storage(tmp_path, monkeypatch)
    from ascend_op_agent.agent.prompt_builder import PromptBuilder

    pb = PromptBuilder()
    out = pb._build_skills_layer(override=None, task_type=None)
    assert "Available Skills" in out
    assert "/learn" in out


def test_degradation_filters_by_task_type_when_over_threshold(tmp_path, monkeypatch):
    """F-4: when self-built > 12 and task_type is set, filter to same-task_type subset."""
    _use_tmp_storage(tmp_path, monkeypatch)
    from ascend_op_agent.agent.prompt_builder import PromptBuilder
    from ascend_op_agent.skills.storage import SkillStorage

    storage = SkillStorage()
    # Create 13 skills: 8 develop + 5 migrate (over threshold 12)
    for i in range(8):
        _create_skill(storage, f"dev-skill-{i:02d}", task_type="develop")
    for i in range(5):
        _create_skill(storage, f"mig-skill-{i:02d}", task_type="migrate")

    pb = PromptBuilder()
    out = pb._build_skills_layer(override=None, task_type="develop")

    # Only develop subset should remain
    assert "dev-skill-00" in out
    assert "dev-skill-07" in out
    assert "mig-skill-00" not in out
    assert "mig-skill-04" not in out


def test_no_degradation_when_under_threshold(tmp_path, monkeypatch):
    """PR-B U3 (R5b) update: task_type 严格命中 — task_type="develop" 时
    即使总数 ≤ HERMES_LAYER_LIMIT=10, mig-* 仍被过滤(R5b 路由命中,非
    PR-A KTD-2 threshold-guarded)。PR-A 的 "≤12 不过滤" 行为已被 R5b 取代。

    8 个 skill (5 dev + 3 mig) + task_type="develop" → 只 dev-* 输出。
    """
    _use_tmp_storage(tmp_path, monkeypatch)
    from ascend_op_agent.agent.prompt_builder import PromptBuilder
    from ascend_op_agent.skills.storage import SkillStorage

    storage = SkillStorage()
    for i in range(8):  # 5 develop + 3 migrate
        _create_skill(
            storage, f"dev-{i:02d}", task_type="develop"
        ) if i < 5 else _create_skill(
            storage, f"mig-{i:02d}", task_type="migrate"
        )

    pb = PromptBuilder()
    out = pb._build_skills_layer(override=None, task_type="develop")

    # R5b 严格命中: 只 dev-*
    assert "dev-00" in out
    assert "mig-05" not in out


def test_no_degradation_when_task_type_missing(tmp_path, monkeypatch):
    """PR-B U3 (R5b) update: task_type=None + R5b HERMES cap=10 适用全部路径。

    PR-A KTD-2 仅在 production path 用 threshold guard;PR-B 让 cap=10 适用
    全部 (含 default path),避免 12+ self-built + 不带 task_type 时也炸预算
    (plan Q2 决议:Layer 6 上限=10 hermes 默认)。

    13 个 self-built + task_type=None → 渲染只前 10 个(skill-00..09),
    11+ 被 cap drop(原 PR-A "task_type=None 兜底全保" 被 PR-B 取代)。
    """
    _use_tmp_storage(tmp_path, monkeypatch)
    from ascend_op_agent.agent.prompt_builder import PromptBuilder
    from ascend_op_agent.skills.storage import SkillStorage

    storage = SkillStorage()
    for i in range(13):
        _create_skill(storage, f"skill-{i:02d}", task_type="develop")

    pb = PromptBuilder()
    out = pb._build_skills_layer(override=None, task_type=None)

    # 前 10 全在
    assert "skill-00" in out
    assert "skill-09" in out
    # 11+ 被 cap drop
    assert "skill-10" not in out
    assert "skill-12" not in out


def test_build_system_prompt_passes_task_type_to_skills_layer(monkeypatch):
    """PR-B U3 update: build_system_prompt 透传 task_type + recent_loads 到 _build_skills_layer。

    PR-A U1 仅 plumbing task_type;PR-B U3 加 recent_loads(R5b 路由命中 R3 最新 5 轮 load)。
    """
    from ascend_op_agent.agent.prompt_builder import PromptBuilder
    from ascend_op_agent.agent.memory import MemoryStore

    captured = {}

    def fake_skills_layer(_self, override=None, task_type=None, recent_loads=None):
        captured["override"] = override
        captured["task_type"] = task_type
        captured["recent_loads"] = recent_loads
        return "MOCK-LAYER-6"

    monkeypatch.setattr(
        PromptBuilder, "_build_skills_layer", fake_skills_layer
    )

    pb = PromptBuilder()
    mem = MemoryStore()

    out = pb.build_system_prompt(
        workspace_path="/tmp", memory_store=mem,
        skills_layer_override="OVR", task_type="develop",
        recent_loads=["recent-a", "recent-b"],
    )
    assert "MOCK-LAYER-6" in out
    assert captured == {
        "override": "OVR",
        "task_type": "develop",
        "recent_loads": ["recent-a", "recent-b"],
    }


def test_self_built_skill_uses_frontmatter_description_in_render(tmp_path, monkeypatch):
    """render_skill_bundle_text reads description first-line; ensure U2 passes
    the Skill's description through (not body content)."""
    _use_tmp_storage(tmp_path, monkeypatch)
    from ascend_op_agent.agent.prompt_builder import PromptBuilder
    from ascend_op_agent.skills.models import Skill
    from ascend_op_agent.skills.storage import SkillStorage

    storage = SkillStorage()
    skill = Skill(
        name="tiling-pitfalls",
        description="Short readable description here.",
        content=VALID_BODY,
        metadata={"task_type": "develop", "topic": "tiling"},
    )
    storage.save_skill(skill, dimension="self_built")

    pb = PromptBuilder()
    out = pb._build_skills_layer(override=None, task_type=None)
    assert "tiling-pitfalls" in out
    assert "Short readable description here." in out


def test_render_reuses_canbot_render_skill_bundle_text(tmp_path, monkeypatch):
    """Verify our Layer 6 looks like cannbot render output format
    (- **name**: desc_first per skill)."""
    _use_tmp_storage(tmp_path, monkeypatch)
    from ascend_op_agent.agent.prompt_builder import PromptBuilder
    from ascend_op_agent.skills.storage import SkillStorage

    storage = SkillStorage()
    _create_skill(storage, "alpha", task_type="develop")
    _create_skill(storage, "beta", task_type="develop")

    pb = PromptBuilder()
    out = pb._build_skills_layer(override=None, task_type=None)
    # Both skills listed with the cannbot-style markdown format
    assert "- **alpha**:" in out
    assert "- **beta**:" in out
